homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

setlocale:
    path:      /setlocale/{language}
    defaults:  { _controller: AppBundle:Default:setLocale }

stream_index:
    path:      /streams
    defaults:  { _controller: AppBundle:Stream:index }
    methods:  [GET]

stream_show:
    path: /stream/{id}
    defaults:  { _controller: AppBundle:Stream:show }
    methods:  [GET]

stream_new:
    path:      /stream
    defaults:  { _controller: AppBundle:Stream:new }
    methods:  [POST]

tag_show:
    path: /tag/{id}
    defaults:  { _controller: AppBundle:Tag:show }
    methods:  [GET]

event_index:
    path:      /events
    defaults:  { _controller: AppBundle:Event:index }
    methods:  [GET]

artist_index:
    path:      /artists
    defaults:  { _controller: AppBundle:Event:index }
    methods:  [GET]

address_index:
    path:      /addresses
    defaults:  { _controller: AppBundle:Event:index }
    methods:  [GET]

# FOS USER
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
