homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

stream_index:
    path:      /streams
    defaults:  { _controller: AppBundle:Stream:index }
    methods:  [GET]

stream_show:
    path: /stream/{id}
    defaults:  { _controller: AppBundle:Stream:show }
    methods:  [GET]

stream_new:
    path:      /stream
    defaults:  { _controller: AppBundle:Stream:new }
    methods:  [POST]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"