# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    app.slugger:
#        class: AppBundle\Utils\Slugger
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    markdown:
        class: AppBundle\Utils\Markdown

    app.twig.app_extension:
        class:     AppBundle\Twig\AppExtension
        arguments: ['@markdown']
        public:    false
        tags:
            - { name: twig.extension }

    app.twig.embed_extension:
        class:     AppBundle\Twig\EmbedExtension
        public:    false
        tags:
            - { name: twig.extension }

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }