# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    app.user_locale_listener:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    markdown:
        class: AppBundle\Utils\Markdown

    app.twig.app_extension:
        class:     AppBundle\Twig\AppExtension
        arguments: ['@markdown']
        public:    false
        tags:
            - { name: twig.extension }

    app.twig.embed_extension:
        class:     AppBundle\Twig\EmbedExtension
        public:    false
        tags:
            - { name: twig.extension }

    app.form.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.tag.manager:
        class: AppBundle\Manager\TagManager
        arguments:
            - '@doctrine.orm.entity_manager'

#    app.tag.repository:
#        class: AppBundle\Repository\TagRepository
#        arguments:
#            - '@doctrine.orm.entity_manager'
#
#    app.user.repository:
#        class: AppBundle\Repository\UserRepository
#        arguments:
#            - '@doctrine.orm.entity_manager'

    app.form.tag_list:
        class: AppBundle\Form\Type\TagListType
        arguments:
            - '@app.form.tag_to_name.transformer'
        tags:
            - { name: form.type, alias: app_tag_list }

    app.form.tag_to_name.transformer:
        class: AppBundle\Form\DataTransformer\TagListTransformer
        arguments:
            - '@app.tag.manager'

    app.form.type.artist_activity:
        class: AppBundle\Form\Type\ArtistActivityType
        arguments:
            - '%artist_activities%'
        tags:
            - { name: form.type }