AppBundle\Entity\Address:
    type:  entity
    table: address
    fields:
        street:
            type: string
            nullable: false
        additional:
            type: string
            nullable: true
        latitude:
            type: float
            nullable: true
        longitude:
            type: float
            nullable: true

    manyToOne:
        city:
            targetEntity: City
            inversedBy: artists
            joinColumn:
                nullable: false
        owner:
            targetEntity: User
            cascade: [persist]
            joinColumn:
                nullable: false

    oneToMany:
        events:
            targetEntity: Event
            mappedBy: address

    manyToMany:
        photos:
            targetEntity: Photo
            joinTable:
                name: address_photo
                joinColumns:
                    event_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    photo_id:
                        referencedColumnName: id