AppBundle\Entity\Artist:
    type:  entity
    table: artist
    fields:
        activity:
            type: string
    oneToOne:
        user:
            targetEntity: User
            cascade: [persist]
            inversedBy: artist
            joinColumn:
                nullable: false
                name: user_id
                referencedColumnName: id

    oneToMany:
        collection:
            targetEntity: Product
            mappedBy: artist

    manyToMany:
        photos:
            targetEntity: Photo
            joinTable:
                name: artist_photo
                joinColumns:
                    event_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    photo_id:
                        referencedColumnName: id