AppBundle\Entity\Like:
    type:  entity
    table: like
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime

    manyToOne:
        user:
            targetEntity: User
            inversedBy: likes
            joinColumn:
                nullable: false
        ressource:
            targetEntity: Ressource
            joinColumn:
                nullable: false

    lifecycleCallbacks:
        prePersist: [setCreatedAt]