AppBundle\Entity\Photo:
    type: entity
    table: photos
    repositoryClass: AppBundle\Repository\PhotoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
            nullable: false
        description:
            type: string
            nullable: true
        imageName:
            type: string
            column: image_name
            length: '255'
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    manyToOne:
        user:
            targetEntity: User
            inversedBy: likes
            joinColumn:
                nullable: false

    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: photos
            joinTable:
                name: photo_tag
                joinColumns:
                    photo_id:
                        referencedColumnName: id
            inverseJoinColumns:
                tag_id:
                    referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [setCreatedAt]
        preUpdate: [setUpdatedAt]