AppBundle\Entity\Photo:
    type: entity
    table: photos
    repositoryClass: AppBundle\Repository\PhotoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'

        imageName:
            type: string
            column: image_name
            length: '255'

        description:
            type: string
            length: '255'

        createdAt:
            type: datetime
            column: published_at

    manyToMany:
        tags:
            targetEntity: Tag
            cascade: [persist]
            inversedBy: photos
            joinTable:
                name: photos_tags
                joinColumns:
                    photo_id:
                        referencedColumnName: id
            inverseJoinColumns:
                tag_id:
                    referencedColumnName: id
        artists:
            targetEntity: Artist
            cascade: [persist]
            inversedBy: photos
            joinTable:
                name: photos_artists
                joinColumns:
                    photo_id:
                        referencedColumnName: id
            inverseJoinColumns:
                artist_id:
                    referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [initCreatedAt]