AppBundle\Entity\Ressource:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
#            length: '32'
            unique: true
            nullable: false
        description:
            type: string
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    lifecycleCallbacks:
        prePersist: [setCreatedAt]
        preUpdate: [setUpdatedAt]