AppBundle\Entity\Stream:
    type: entity
    table: streams
    repositoryClass: AppBundle\Repository\StreamRepository
    fields:
        expiration:
            type: datetime
            nullable: true

    manyToOne:
        user:
            targetEntity: User
            inversedBy: streams
            joinColumn:
                name: user_id
                referencedColumnName: id

    manyToMany:
        tags:
            targetEntity: Tag
            cascade: [persist]
            inversedBy: streams
            joinTable:
                name: stream_tag
                joinColumns:
                    stream_id:
                        referencedColumnName: id
            inverseJoinColumns:
                tag_id:
                    referencedColumnName: id