AppBundle\Entity\Stream:
    type: entity
    table: streams
    repositoryClass: AppBundle\Repository\StreamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: string
            length: '255'

        publishedAt:
            type: datetime
            column: published_at

    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: streams
            joinTable:
                name: streams_tags
                joinColumns:
                    stream_id:
                        referencedColumnName: id
            inverseJoinColumns:
                tag_id:
                    referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [initPublishedAtValue]