AppBundle\Entity\Stream:
    type: entity
    table: streams
    repositoryClass: AppBundle\Repository\StreamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        description:
            type: string

        createdAt:
            type: datetime
            column: created_at

    manyToOne:
        user:
            targetEntity: User
            inversedBy: streams
            joinColumn:
                name: user_id
                referencedColumnName: id

    manyToMany:
        tags:
            targetEntity: Tag
            cascade: [persist]
            inversedBy: streams
            joinTable:
                name: streams_tags
                joinColumns:
                    stream_id:
                        referencedColumnName: id
            inverseJoinColumns:
                tag_id:
                    referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [initCreatedAt]