AppBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '32'
            unique: true

    manyToMany:
        streams:
            targetEntity: Stream
            mappedBy: tags
        photos:
            targetEntity: Photo
            mappedBy: tags

    lifecycleCallbacks:
        prePersist: [setCreatedAt]