AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

#    fields:
#        name:
#            type: string
#            length: '32'
#            unique: true
#
#  oneToMany:
#      streams:
#          targetEntity: Stream
#          mappedBy: user
#
#  oneToMany:
#      photos:
#          targetEntity: Photo
#          mappedBy: user