AppBundle\Entity\User:
    type:  entity
    repositoryClass: AppBundle\Repository\UserRepository
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        locale:
            type: string
            length: '2'
            nullable: false

        createdAt:
            column: created_at
            type: datetime

    oneToOne:
        artist:
            targetEntity: Artist
            mappedBy: user

#  oneToMany:
#      streams:
#          targetEntity: Stream
#          mappedBy: user
#
#  oneToMany:
#      photos:
#          targetEntity: Photo
#          mappedBy: user

    lifecycleCallbacks:
        prePersist: [setCreatedAt]